
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces
      # X11 forwarding volumes
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/home/node/.Xauthority:ro
    environment:
      # X11 forwarding environment
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/home/node/.Xauthority
      - CYPRESS_CACHE_FOLDER=/home/node/.cache/Cypress
    
    # Additional options for X11
    ipc: host
    network_mode: host
    
    # Security options for X11
    security_opt:
      - seccomp:unconfined
    
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: mongo:8.0.10
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

    # Uncomment to change startup options
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: your-database-here

volumes:
  mongodb-data: