
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mongo:8.0.10
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      - ./mongodb/rs-initiate.js:/docker-entrypoint-initdb.d/rs-initiate.js
    command: ["--replSet", "dbrs", "--bind_ip_all"]
    

volumes:
  mongodb-data: