
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
  # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mongo:8.0.10
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    command: ["--replSet", "dbrs", "--bind_ip_all"]
  db-replica-init:
    image: mongo:8.0.10
    volumes:
      - ./mongodb/rs-initiate.js:/rs-initiate.js
    depends_on:
      - db
    entrypoint: bash -c "sleep 10 && mongosh --host db:27017 /rs-initiate.js"
    

volumes:
  mongodb-data: